_homepage:
    path:     /
    defaults: { _controller: MDPIEsBundle:HomePage:index}

_history:
    path:     /about/history
    defaults: { _controller: MDPIEsBundle:AboutPage:history}
    
_profile:
    path:     /about/company-profile
    defaults: { _controller: MDPIEsBundle:AboutPage:profile}
    
_team:
    path:     /about/team
    defaults: { _controller: MDPIEsBundle:AboutPage:team}
    
_journals:
    path:     /about/journals
    defaults: { _controller: MDPIEsBundle:AboutPage:journals}
    
_contact:
    path:     /contact
    defaults: { _controller: MDPIEsBundle:ContactPage:contact}


_jobs:
    path:     /jobs
    defaults: { _controller: MDPIEsBundle:JobsPage:jobs}


